import '@/app/globals.css';
import Bottombar from '@/components/Bottombar/Bottombar';
import Sidebar from '@/components/Sidebar/Sidebar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.layout}>
          <Sidebar />
          <section className={styles.container}>{children}</section>
          <Bottombar />
        </div>
      </body>
    </html>
  );
}
